[package]
name = "disable-sni-reverse-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ctrlc = "1.2.0"
dirs-next = "2.0.0"
futures = "0.3.21"
once_cell = "1.10.0"
pretty_env_logger = "0.4.0"
rcgen = { version = "0.9.2", features = ["pem", "x509-parser"] }
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["__rustls", "brotli"] }
rustls = "0.20.4"
serde = "1.0.136"
serde_derive = "1.0.136"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
toml = "0.5.9"
tracing = "0.1.34"
warp = { version = "0.3.2", features = ["tls"] }
warp-reverse-proxy = { git = "https://github.com/shanmiteko/warp-reverse-proxy.git" }
webpki-roots = "0.22.3"
