name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  release-name: snimap

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    # Cache cargo registry, index, and build
    - name: Retrieve Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # Build
    - name: Cargo Build
      run: cargo build --verbose --release

    # Copy files
    - name: Copy artifacts
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          cp target/debug/${{ env.release-name }}.exe public
        else
          cp target/debug/${{ env.release-name }} public
        fi
        cp private/ca.crt public
        cp README.md public

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: public
