name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  release-name: snimap

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Install Rust toolchain (nightly channel)
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    # Cache cargo registry, index, and build
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # Build
    - name: Build
      run: cargo build --verbose

    # Test
    - name: Run tests
      run: cargo test --verbose

    # Copy files
    - name: Copy artifacts
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          cp target/debug/${{ env.release-name }}.exe ${{ runner.temp }}
        else
          cp target/debug/${{ env.release-name }} ${{ runner.temp }}
        fi
        cp private/ca.crt ${{ runner.temp }}
        cp README.md ${{ runner.temp }}

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-${{ matrix.os }}
        path: ${{ runner.temp }}/*
